services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      FAST_REFRESH: false
      WDS_SOCKET_PORT: 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: on-failure
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata: