import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import {CssBaseline, ThemeProvider} from "@mui/material";
import theme from './theme';
import ThemeRegistry from "@/app/ThemeRegistry";

export const metadata = {
  title: "gkorm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <title>gkorm</title>
      </head>
      <body  style={{ fontFamily: 'Roboto, sans-serif' }}>
      <ThemeRegistry>
          {children}
      </ThemeRegistry>
      </body>
    </html>
  );
}
